# Generated by Django 5.1.1 on 2025-01-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='qr_secret',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
