# Generated by Django 5.1.1 on 2025-01-27 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_qr_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='photo',
        ),
    ]
