# Generated by Django 5.1.1 on 2025-02-01 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_reservation_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('unique_id', models.CharField(max_length=100, unique=True)),
                ('address', models.TextField()),
                ('max_slots', models.IntegerField()),
                ('reserved_slots', models.IntegerField(default=0)),
                ('unavailable_days', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='slot',
            name='parking_lot',
        ),
        migrations.AddField(
            model_name='slot',
            name='parking_place',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='user.parkingplace'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='parking_lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='user.parkingplace'),
        ),
        migrations.DeleteModel(
            name='ParkingLot',
        ),
    ]
