# Generated by Django 5.1.1 on 2025-03-20 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_reservation_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationlog',
            name='qr_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservationlog',
            name='parking_lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.parkingplace'),
        ),
        migrations.AlterField(
            model_name='reservationlog',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.slot'),
        ),
    ]
