# Generated by Django 5.1.1 on 2025-03-20 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_reservationlog_qr_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationlog',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservationlog',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
